# **Tourism Experience Analytics: Classification, Prediction, and Recommendation System**

### Importing libraries

In [ ]:
import pandas as pd
import os

### Loading files from drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data_path="/content/drive/MyDrive/datasets/Tourism Dataset/raw_data"
files=os.listdir(data_path)
files

['Transaction.xlsx',
 'Mode.xlsx',
 'Type.xlsx',
 'Country.xlsx',
 'Continent.xlsx',
 'Region.xlsx',
 'User.xlsx',
 'City.xlsx',
 'Updated_item.xlsx']

### 1. Transaction dataset

In [ ]:
df_transactions=pd.read_excel(f"{data_path}/Transaction.xlsx")
df_transactions.head()

,TransactionId,UserId,VisitYear,VisitMonth,VisitMode,AttractionId,Rating
0,3,70456,2022,10,2,640,5
1,8,7567,2022,10,4,640,5
2,9,79069,2022,10,3,640,5
3,10,31019,2022,10,3,640,3
4,15,43611,2022,10,2,640,3

In [ ]:
df_transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52930 entries, 0 to 52929
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TransactionId  52930 non-null  int64
 1   UserId         52930 non-null  int64
 2   VisitYear      52930 non-null  int64
 3   VisitMonth     52930 non-null  int64
 4   VisitMode      52930 non-null  int64
 5   AttractionId   52930 non-null  int64
 6   Rating         52930 non-null  int64
dtypes: int64(7)
memory usage: 2.8 MB

In [ ]:
df_transactions.describe()

,TransactionId,UserId,VisitYear,VisitMonth,VisitMode,AttractionId,Rating
count,52930.000000,52930.000000,52930.000000,52930.000000,52930.000000,52930.000000,52930.000000
mean,70415.130474,45024.522596,2016.351899,6.633100,2.945759,759.663782,4.157699
std,66299.514206,25073.062199,1.732926,3.392979,1.000683,210.716111,0.970543
min,3.000000,14.000000,2013.000000,1.000000,1.000000,369.000000,1.000000
25%,19646.250000,23470.000000,2015.000000,4.000000,2.000000,640.000000,4.000000
50%,42770.500000,45533.500000,2016.000000,7.000000,3.000000,737.000000,4.000000
75%,105638.750000,66667.000000,2018.000000,9.000000,4.000000,841.000000,5.000000
max,211241.000000,88190.000000,2022.000000,12.000000,5.000000,1297.000000,5.000000

In [ ]:
df_transactions.isnull().sum()

TransactionId    0
UserId           0
VisitYear        0
VisitMonth       0
VisitMode        0
AttractionId     0
Rating           0
dtype: int64

In [ ]:
df_transactions.duplicated().sum()

np.int64(0)

This dataset is already cleaned , there are no missing values , no duplicates and all columns are of integer data type , so cleaning is not required.

### 2. Mode dataset

In [ ]:
df_mode=pd.read_excel(f"{data_path}/Mode.xlsx")
df_mode.head(6)

   VisitModeId VisitMode
0            0         -
1            1  Business
2            2   Couples
3            3    Family
4            4   Friends
5            5      Solo

In [ ]:
df_mode.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   VisitModeId  6 non-null      int64
 1   VisitMode    6 non-null      object
dtypes: int64(1), object(1)
memory usage: 228.0+ bytes

In [ ]:
df_mode.describe()

       VisitModeId
count     6.000000
mean      2.500000
std       1.870829
min       0.000000
25%       1.250000
50%       2.500000
75%       3.750000
max       5.000000

In [ ]:
df_mode.isnull().sum()

VisitModeId    0
VisitMode      0
dtype: int64

In [ ]:
df_mode.duplicated().sum()

np.int64(0)

In [ ]:
df_mode.value_counts()

VisitModeId  VisitMode
0            -            1
1            Business     1
2            Couples      1
3            Family       1
4            Friends      1
5            Solo         1
Name: count, dtype: int64

In [ ]:
df_mode['VisitMode']=df_mode['VisitMode'].replace("-",'Unknown')

#### 3. Type Dataset

In [ ]:
df_type=pd.read_excel(f"{data_path}/Type.xlsx")
df_type.head()

   AttractionTypeId         AttractionType
0                 2          Ancient Ruins
1                10                Ballets
2                13                Beaches
3                19        Caverns & Caves
4                34  Flea & Street Markets

In [ ]:
df_type.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   AttractionTypeId  17 non-null     int64
 1   AttractionType    17 non-null     object
dtypes: int64(1), object(1)
memory usage: 404.0+ bytes

In [ ]:
df_type.describe()

       AttractionTypeId
count         17.000000
mean          55.588235
std           30.761296
min            2.000000
25%           34.000000
50%           63.000000
75%           82.000000
max           93.000000

In [ ]:
df_type.isna().sum()

AttractionTypeId    0
AttractionType      0
dtype: int64

In [ ]:
df_type.duplicated().sum()

np.int64(0)

In [ ]:
df_type.value_counts()

AttractionTypeId  AttractionType
2                 Ancient Ruins                     1
10                Ballets                           1
13                Beaches                           1
19                Caverns & Caves                   1
34                Flea & Street Markets             1
44                Historic Sites                    1
45                History Museums                   1
61                National Parks                    1
63                Nature & Wildlife Areas           1
64                Neighborhoods                     1
72                Points of Interest & Landmarks    1
76                Religious Sites                   1
82                Spas                              1
84                Speciality Museums                1
91                Volcanos                          1
92                Water Parks                       1
93                Waterfalls                        1
Name: count, dtype: int64

### 4. Country Dataset

In [ ]:
df_country=pd.read_excel(f"{data_path}/Country.xlsx")
df_country.head()

   CountryId   Country  RegionId
0          0         -         0
1          1  Cameroon         1
2          2      Chad         1
3          3    Rwanda         1
4          4  Ethiopia         2

In [ ]:
df_country.value_counts()

CountryId  Country         RegionId
0          -               0           1
1          Cameroon        1           1
2          Chad            1           1
3          Rwanda          1           1
4          Ethiopia        2           1
                                      ..
160        Ireland         21          1
161        Monaco          21          1
162        Netherlands     21          1
163        United Kingdom  21          1
164        Yemen           12          1
Name: count, Length: 165, dtype: int64

In [ ]:
df_country["Country"] = df_country["Country"].replace("-", "Unknown")

In [ ]:
df_country.describe()

        CountryId    RegionId
count  165.000000  165.000000
mean    82.000000   11.430303
std     47.775517    5.905996
min      0.000000    0.000000
25%     41.000000    6.000000
50%     82.000000   12.000000
75%    123.000000   17.000000
max    164.000000   21.000000

### 5. Continent dataset

In [ ]:
df_continent=pd.read_excel(f"{data_path}/Continent.xlsx")
df_continent.head()

   ContinentId            Continent
0            0                    -
1            1               Africa
2            2              America
3            3                 Asia
4            4  Australia & Oceania

In [ ]:
df_continent.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ContinentId  6 non-null      int64
 1   Continent    6 non-null      object
dtypes: int64(1), object(1)
memory usage: 228.0+ bytes

In [ ]:
df_continent.describe()

       ContinentId
count     6.000000
mean      2.500000
std       1.870829
min       0.000000
25%       1.250000
50%       2.500000
75%       3.750000
max       5.000000

In [ ]:
df_continent.isna().sum()

ContinentId    0
Continent      0
dtype: int64

In [ ]:
df_continent.duplicated().sum()

np.int64(0)

In [ ]:
df_continent["Continent"] = df_continent["Continent"].replace("-", "Unknown")

### 6. Region Dataset

In [ ]:
df_region=pd.read_excel(f"{data_path}/Region.xlsx")
df_region.head()

            Region  RegionId  ContinentId
0                -         0            0
1   Central Africa         1            1
2      East Africa         2            1
3     North Africa         3            1
4  Southern Africa         4            1

In [ ]:
df_region.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Region       22 non-null     object
 1   RegionId     22 non-null     int64
 2   ContinentId  22 non-null     int64
dtypes: int64(2), object(1)
memory usage: 660.0+ bytes

In [ ]:
df_region.describe()

        RegionId  ContinentId
count  22.000000    22.000000
mean   10.500000     2.772727
std     6.493587     1.601541
min     0.000000     0.000000
25%     5.250000     1.250000
50%    10.500000     3.000000
75%    15.750000     4.000000
max    21.000000     5.000000

In [ ]:
df_region.isnull().sum()

Region         0
RegionId       0
ContinentId    0
dtype: int64

In [ ]:
df_region.duplicated().sum()

np.int64(0)

In [ ]:
df_region["Region"] = df_region["Region"].replace("-", "Unknown")

### 7. User dataset

In [ ]:
df_user=pd.read_excel(f"{data_path}/User.xlsx")
df_user.head()

   UserId  ContinentId  RegionId  CountryId  CityId
0      14            5        20        155   220.0
1      16            3        14        101  3098.0
2      20            4        15        109  4303.0
3      23            1         4         22   154.0
4      25            3        14        101  3098.0

In [ ]:
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33530 entries, 0 to 33529
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   UserId       33530 non-null  int64
 1   ContinentId  33530 non-null  int64
 2   RegionId     33530 non-null  int64
 3   CountryId    33530 non-null  int64
 4   CityId       33526 non-null  float64
dtypes: float64(1), int64(4)
memory usage: 1.3 MB

Why CityId is float64 (important insight ) ?

CityId became float64 only because of NaN.

Pandas rule:

- Integer column + NaN → converted to float

So this is not a data design issue, just a missing-value side effect.

In [ ]:
df_user.describe()

             UserId   ContinentId      RegionId     CountryId        CityId
count  33530.000000  33530.000000  33530.000000  33530.000000  33526.000000
mean   45112.842231      3.601044     14.534864    106.360871   3409.146841
std    24904.878706      1.066745      4.148320     35.392048   2313.002950
min       14.000000      1.000000      0.000000      1.000000      1.000000
25%    23825.250000      3.000000     13.000000     93.000000   1434.000000
50%    45556.500000      4.000000     15.000000    109.000000   3206.000000
75%    66636.250000      4.000000     16.000000    115.000000   4940.000000
max    88190.000000      5.000000     21.000000    164.000000   9142.000000

In [ ]:
df_user.isnull().sum()

UserId         0
ContinentId    0
RegionId       0
CountryId      0
CityId         4
dtype: int64

In [ ]:
df_user[df_user["CityId"].isna()]

       UserId  ContinentId  RegionId  CountryId  CityId
2279     7175            5        17        135     NaN
6027    17595            1         4         22     NaN
21303   56972            5        17        135     NaN
25494   67461            5        17        135     NaN

In [ ]:
df_user = df_user.dropna(subset=["CityId"]).copy()
df_user['CityId'] = df_user['CityId'].astype(int)

“The user dataset had 4 missing CityId values (0.01%). Since they were negligible and not critical, those rows were removed to preserve data integrity and consistent data types.”

In [ ]:
df_user.duplicated().sum()

np.int64(0)

### 8. City dataset

In [ ]:
df_city=pd.read_excel(f"{data_path}/City.xlsx")
df_city.head()

   CityId      CityName  CountryId
0       0             -          0
1       1        Douala          1
2       2  South Region          1
3       3     N'Djamena          2
4       4        Kigali          3

In [ ]:
df_city.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9143 entries, 0 to 9142
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CityId     9143 non-null   int64
 1   CityName   9142 non-null   object
 2   CountryId  9143 non-null   int64
dtypes: int64(2), object(1)
memory usage: 214.4+ KB

In [ ]:
df_city.describe()

            CityId    CountryId
count  9143.000000  9143.000000
mean   4571.000000   107.776878
std    2639.501089    42.466496
min       0.000000     0.000000
25%    2285.500000    69.000000
50%    4571.000000   109.000000
75%    6856.500000   151.000000
max    9142.000000   164.000000

In [ ]:
df_city.isnull().sum()

CityId       0
CityName     1
CountryId    0
dtype: int64

In [ ]:
df_city['CityName']=df_city['CityName'].fillna('Unknown')

In [ ]:
df_city["CityName"] = df_city["CityName"].replace("-", "Unknown")

In [ ]:
df_city.duplicated().sum()

np.int64(0)

### 9. Item Dataset

In [ ]:
df_item=pd.read_excel(f"{data_path}/Updated_item.xlsx")
df_item.head()

,AttractionId,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress
0,369,1,13,Kuta Beach - Bali,Kuta
1,481,1,13,Nusa Dua Beach,"Semenanjung Nusa Dua, Nusa Dua 80517 Indonesia"
2,640,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia"
3,650,1,13,Sanur Beach,Sanur
4,673,1,13,Seminyak Beach,Seminyak

In [ ]:
df_item.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   AttractionId       30 non-null     int64
 1   AttractionCityId   30 non-null     int64
 2   AttractionTypeId   30 non-null     int64
 3   Attraction         30 non-null     object
 4   AttractionAddress  30 non-null     object
dtypes: int64(3), object(2)
memory usage: 1.3+ KB

In [ ]:
df_item.describe()

       AttractionId  AttractionCityId  AttractionTypeId
count     30.000000         30.000000         30.000000
mean     936.266667          2.000000         51.333333
std      243.316161          0.830455         32.286790
min      369.000000          1.000000          2.000000
25%      767.750000          1.000000         13.000000
50%      924.000000          2.000000         62.000000
75%     1158.750000          3.000000         76.000000
max     1297.000000          3.000000         93.000000

In [ ]:
df_item.duplicated().sum()

np.int64(0)

### Saving cleaned files in a new data folder

In [ ]:
clean_path="/content/drive/MyDrive/datasets/Tourism Dataset/cleaned_data"

In [ ]:
cleaned_dfs = {
    "transactions" : df_transactions,
    "mode" : df_mode,
    "type" : df_type,
    "continent" : df_continent,
    "country": df_country,
    "city" : df_city,
    "region": df_region,
    "user": df_user,
    "item": df_item
}
for name, df in cleaned_dfs.items():
    df.to_csv(f"{clean_path}/{name}_clean.csv", index=False)